update news vbump to 0.8.5, [skip vbump]
insightsengineering/tern pull request #1008
Opened 2023-07-20 06:59 UTC by shajoezhu

# Pull Request

Fixes #nnn

2023-07-20 16:33 UTC, edelarua requested changes
Just a suggestion to improve organization of the NEWS file

2023-07-20 16:33 UTC, edelarua commented on NEWS.md
> +### Miscellaneous
```suggestion
### Enhancements
```

2023-07-20 16:33 UTC, edelarua commented on NEWS.md
>  * Added `flag_labels` argument to `s_count_patients_with_flags` to enable more label handling options in `count_patients_by_flags`.
```suggestion
* Added `ylim` argument to `g_km` to allow the user to set custom limits for the y-axis.
* Added assertion to `g_km` which checks whether there is one arm present in the data when `annot_coxph` is true.
* Added `flag_labels` argument to `s_count_patients_with_flags` to enable more label handling options in `count_patients_by_flags`. 

### Miscellaneous
* Started deprecation cycle for `summarize_vars` and `control_summarize_vars`. Renamed into `analyze_vars` and `control_analyze_vars` to reflect underlying `rtables` machinery while keeping backward compatibility with aliases.
```

2023-07-20 20:21 UTC, edelarua approved these changes
Approving to unblock

2023-07-21 04:39 UTC, shajoezhu commented
Thanks a lot @edelarua

2023-07-24 03:30 UTC, merged