Add helper functions to refactor PKCT01
insightsengineering/tern pull request #1048
Opened 2023-08-31 01:16 UTC by edelarua

Closes #277 #543 

In this PR: 

- Added `imputation_rule` function to perform 1/3 and 1/2 imputation rule calculations.
- Added `format_sigfig` formatting function to format numeric values by number of significant digits.
- Updated calculation of `geom_mean` to return 0 instead of `NA` in cases of all-zero data.
- Updated `analyze_vars_in_cols` to add `.aligns` argument, option to implement imputation rule (`imp_rule`), and use caching.

To merge after CRAN release.

2023-08-31 16:52 UTC, Melkiades commented on R/analyze_vars_in_cols.R
> +  env <- new.env() # create caching environment
Do we still need to cache the env? I do not remember why we added it

2023-08-31 16:53 UTC, edelarua commented on R/analyze_vars_in_cols.R
> +  env <- new.env() # create caching environment
I just added that in because otherwise it calculates every statistic for every cell. Using caching it will only calculate every statistic once per row.

2023-08-31 16:57 UTC, Melkiades commented on R/analyze_vars_in_cols.R
> +  env <- new.env() # create caching environment
Ah yes now I remember, it was needed for "computing time"

2023-09-06 07:49 UTC, Melkiades commented on R/analyze_vars_in_cols.R
>        stop("When using do_summarize_row_groups only one label level var should be inserted.")
I am so skeptical about using this duplication these days. We will have to change this in the future

2023-09-06 07:49 UTC, Melkiades commented on R/analyze_vars_in_cols.R
> +          )
I am just wondering if there is not a simpler way to do this

2023-09-06 08:03 UTC, Melkiades commented on R/imputation_rule.R
> +
This is a condensed version of https://github.com/insightsengineering/tern/issues/543

do you think we could test against that long list?

2023-09-06 08:03 UTC, Melkiades approved these changes
Lgtm! Great work! :) Thanks Emily

2023-09-06 13:22 UTC, edelarua commented on R/imputation_rule.R
> +
I tried to keep track from the list using the comments beside each line (e.g. `1/3_pre_LT` = 1/3 imputation rule, pre-dose, less than 1/3) but it's still a bit difficult to check each case.

2023-09-06 13:26 UTC, edelarua commented on R/analyze_vars_in_cols.R
> +          )
Yeah I'm not sure if there's a simpler way but the problem arises from variables that are used in multiple columns - i.e. we sometimes have just `AVAL`, sometimes will have `AVAL._[[1]]_.`, `AVAL._[[2]]_.`, `AVAL._[[3]]_.`, etc. - and then I didn't want any errors occurring if there's a `.` in a regular variable name.

2023-09-06 14:06 UTC, Melkiades commented on R/imputation_rule.R
> +
yep also for me, maybe keeping the list as a tested ref?

2023-09-06 14:08 UTC, Melkiades commented on R/analyze_vars_in_cols.R
> +          )
I see! It makes sense but I believe this happens only with split_by_multivars

2023-09-06 16:26 UTC, anajens commented
Hi @edelarua , please don't merge just yet. I've been using this branch to QC the table with real data (https://github.com/insightsengineering/sme-tasks/issues/184) and I am having some trouble with `.aligns`. Will tag you in the issue when I create it.

2023-09-06 18:03 UTC, anajens requested changes
Here's an example of the error I see when testing this branch:

```
library(dplyr)

anl <- data.frame(
  AVAL = c(419000, 569000, 379000)
)

lyt <- basic_table() %>%
  analyze_vars_in_cols(
    vars = "AVAL",
    .stats = c("n", "mean", "sd"),
    .formats = c(n = "xx.", mean = format_sigfig(3), sd = format_sigfig(3)),
    .aligns = "decimal"
  )

build_table(lyt = lyt, df = anl)
```

Error:
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'toString': Decimal alignment is not supported for multiple values. Found the following string with multiple numbers (first 3 selected from column SD): '1e+05', 'NA', 'NA'
```

Can see result with `aligns = NULL`
```
       n    Mean     SD  
—————————————————————————
root   3   456000   1e+05
```

2023-09-06 19:17 UTC, edelarua commented
> Here's an example of the error I see when testing this branch:
> 
> ```
> library(dplyr)
> 
> anl <- data.frame(
>   AVAL = c(419000, 569000, 379000)
> )
> 
> lyt <- basic_table() %>%
>   analyze_vars_in_cols(
>     vars = "AVAL",
>     .stats = c("n", "mean", "sd"),
>     .formats = c(n = "xx.", mean = format_sigfig(3), sd = format_sigfig(3)),
>     .aligns = "decimal"
>   )
> 
> build_table(lyt = lyt, df = anl)
> ```
> 
> Error:
> 
> ```
> Error in h(simpleError(msg, call)) : 
>   error in evaluating the argument 'x' in selecting a method for function 'toString': Decimal alignment is not supported for multiple values. Found the following string with multiple numbers (first 3 selected from column SD): '1e+05', 'NA', 'NA'
> ```

It seems like it's caused by the combination of the formatting function (`format_sigfig`) and the decimal alignment since changing either one will fix it. 

@ayogasekaram @Melkiades do you have any insight into why this would happen with the decimal alignment? The formatting function converts to character. Strangely, this error does not occur in the PKCT01 table.

2023-09-06 19:58 UTC, anajens commented on R/imputation_rule.R
> +  checkmate::assert_choice("AVALCAT1", names(df))
The variable name should not be hardcoded.

2023-09-06 20:41 UTC, anajens commented on R/imputation_rule.R
> +imputation_rule <- function(df, x_stats, stat, imp_rule, post = FALSE) {
GDS_PK_TLG_Specification (link in #543) document describes using the variable `FLAGSUM` to control the display of summary statistics. How does this fit in with this function?

2023-09-06 20:56 UTC, edelarua commented on R/imputation_rule.R
> +imputation_rule <- function(df, x_stats, stat, imp_rule, post = FALSE) {
Translating from the spec. document linked in #543, in our data `SUMMCONC` is replaced with `AVAL`, `NOMTIME` is replaced by `NFRLT`, and `FLAGSUM` is `n_blq` derived within the function (sum of flagged values).

2023-09-06 21:04 UTC, anajens commented on R/imputation_rule.R
> +imputation_rule <- function(df, x_stats, stat, imp_rule, post = FALSE) {
I think deriving an equivalent of `FLAGSUM` within the analysis function is risky since the code list of strings of what is considered "BLQ" is not standardized and it's possible that there are data with values other than "BLQ", "LTR", "<PCLLOQ"  (@qiliu1013 can you confirm?)

I suggest to use the variable directly from the analysis data rather than re-deriving it.

2023-09-06 21:46 UTC, edelarua commented on R/imputation_rule.R
> +imputation_rule <- function(df, x_stats, stat, imp_rule, post = FALSE) {
I've updated the function to use `FLAGSUM` (not hard-coded). I'm not sure if this is a standard variable, but if not we can just revert the change.

2023-09-07 08:10 UTC, Melkiades commented
> @ayogasekaram @Melkiades do you have any insight into why this would happen with the decimal alignment? The formatting function converts to character. Strangely, this error does not occur in the PKCT01 table.

Yes, I know why exactly. It is that we should avoid using scientific notation for decimal alignments and `as.character` does it. I am preparing a fix in `formatters` to deal with this. Just a question for @anajens: is it always to avoid the scientific numeric representation?

2023-09-07 10:41 UTC, Melkiades commented on R/formatting_functions.R
> +    as.character(signif(x, sigfig))
```suggestion
    formatC(x, digits = sigfig, format = "f")
```

2023-09-07 13:17 UTC, Melkiades commented on R/formatting_functions.R
> +    as.character(signif(x, sigfig))
This should fix it

2023-09-07 13:17 UTC, Melkiades commented on R/imputation_rule.R
> +
@qiliu1013 checked the output in the final print and it seems fine! 👍

2023-09-07 14:15 UTC, anajens commented
>Just a question for @anajens: is it always to avoid the scientific numeric representation?

@Melkiades formatters should be able to handle scientific notation alignment as it's supposed to be a general purpose package and not necessarily supporting only the roche standards

2023-09-07 14:45 UTC, Melkiades commented
> > Just a question for @anajens: is it always to avoid the scientific numeric representation?
> 
> @Melkiades formatters should be able to handle scientific notation alignment as it's supposed to be a general purpose package and not necessarily supporting only the roche standards

It does handle them. Only the decimal alignment is not thinking about it (I did not when reworking it in). I was just wondering if in general they should be disabled generally. I am adding the possibility of having scientific notation and decimal alignment (i.e. transform the scientific notation in numeric, then format it

2023-09-07 16:51 UTC, edelarua commented on R/imputation_rule.R
> +imputation_rule <- function(df, x_stats, stat, imp_rule, post = FALSE) {
@anajens after talking to Qi I have reverted this - `FLAGSUM` is no longer a standard variable and `AVALCAT1` should be used instead.

2023-09-07 16:55 UTC, edelarua commented
@anajens regarding row counts in PKCT01 - Qi has indicated that this is a must-have so I have refactored `add_rowcounts` to suit our purposes (just need to specify `alt_counts = TRUE` if `alt_counts_df` counts should be used). See the updated snapshots which include row counts (values unchanged) [here](https://github.com/insightsengineering/tlg-catalog/pull/104/files#diff-ed139c336043416042a18ca53ef3e0b73eec9be56dc3a30b470f2bc64c62e940).

2023-09-07 17:00 UTC, edelarua commented on R/formatting_functions.R
> +    as.character(signif(x, sigfig))
I modified this a bit but it's now working. Thanks!

2023-09-08 15:41 UTC, anajens commented on R/analyze_vars_in_cols.R
> +              imp_rule = imp_rule, post = as.numeric(tail(.spl_context$value, 1)) > 0
Please add `avalcat_var` here so user can select a different value from the default AVALCAT1 if necessary.

2023-09-08 16:42 UTC, anajens reviewed
I'm seeing something very weird with re-using the same layout with `analyze_vars_in_cols` on different data sets. @edelarua Can you replicate this?

```
anl1 <- data.frame(AVAL = c(100, 200, 300))
anl2 <- data.frame(AVAL = c(1, 2, 3))

lyt <- basic_table() %>%
  analyze_vars_in_cols(
    vars = "AVAL",
    .stats = c("n", "mean", "sd"),
    .formats = c(n = "xx.", mean = "xx.x", sd = "xx.x"))

build_table(lyt = lyt, df = anl1)
build_table(lyt = lyt, df = anl2)

```
Tables are identical?! 
```
> build_table(lyt = lyt, df = anl1)
       n   Mean     SD  
————————————————————————
root   3   200.0   100.0
> build_table(lyt = lyt, df = anl2)
       n   Mean     SD  
————————————————————————
root   3   200.0   100.0
```

2023-09-08 16:53 UTC, edelarua commented
> I'm seeing something very weird with re-using the same layout with `analyze_vars_in_cols` on different data sets. 

Hi @anajens,

I noticed that as well - it was a side effect of caching while using the same layout. It is fixed now (by https://github.com/insightsengineering/tern/pull/1048/commits/cbfb9aa095fa5a0da13dda7f3c4aaaccaeb9be4d) since I turned off caching by default. I have also exposed the `avalcat_var` argument in `analyze_vars_in_cols`.

2023-09-08 17:23 UTC, anajens commented on R/analyze_vars_in_cols.R
> +#'   for more details on imputation.
```suggestion
#'   to use an imputation rule, the `avalcat_var` argument must be specified. See [imputation_rule()]
#'   for more details on imputation.
```

2023-09-08 18:23 UTC, anajens approved these changes
Thanks for all the updates @edelarua

2023-09-08 19:11 UTC, merged

2023-09-11 17:27 UTC, Melkiades commented on R/formatting_functions.R
> +    as.character(signif(x, sigfig))
@edelarua just for better understanding, why did you modify it specifically? I am reading the docs but I find hard figuring out use cases ^^