Reorganize and group defaults for stats and their default formats/labels -> addition of auto for DMT01
insightsengineering/tern pull request #1051
Opened 2023-08-31 17:25 UTC by Melkiades

Fixes #994 (for now)

2023-08-31 18:45 UTC, pawelru commented on R/utils_defaults_handling.R
> +tern_default_formats <- function() {
why a function and not a value?

2023-09-01 08:21 UTC, Melkiades commented on R/utils_defaults_handling.R
> +tern_default_formats <- function() {
No particular reason. Do you prefer it as a value? maybe having it as a function clarifies that is a package-wise thing and not a local definition. But it is fine ofc either ways

2023-09-01 08:26 UTC, pawelru commented on R/utils_defaults_handling.R
> +tern_default_formats <- function() {
This is not a strong preference but rather an observation. This function neither take arguments nor is influenced from the outside via e.g. options or sys env. Hence it's a _constant_ and such constant values are definitely a package thing. You can do roxygen docs, export etc.

2023-09-01 10:40 UTC, Melkiades commented on R/utils_defaults_handling.R
> +tern_default_formats <- function() {
I needed a flag for different values so now it makes sense!

2023-09-06 07:16 UTC, Melkiades commented on NEWS.md
> +* Added getters for formats `get_format_from_stats()` and labels `get_labels_from_formats()`.
```suggestion
* Added getters for formats `get_format_from_stats()` and labels `get_labels_from_stats()`.
```

2023-09-06 14:22 UTC, Melkiades commented on R/summary_stats.R
>  summary_formats <- function(type = "numeric", include_pval = FALSE) {
@edelarua This file can be probably removed and the shorthand for summary can be moved (I would keep it)

2023-09-06 14:23 UTC, Melkiades commented on R/analyze_variables.R
> +a_summary <- function(x,
This can be removed too imo @edelarua

2023-09-06 15:12 UTC, Melkiades commented on R/utils_defaults_handling.R
> +  }
The pval treatment is a bit unstable @edelarua

2023-09-06 15:13 UTC, Melkiades commented on R/utils_defaults_handling.R
> +  pval_counts = "x.xxxx | (<0.0001)"
The only difference is in labels

2023-09-06 15:14 UTC, Melkiades commented on R/utils_defaults_handling.R
> +        "analyze_vars_numeric" = c(
@edelarua names are at the moment these and can be expanded and changed with a list of possibility to add to the docs. e.g. count/count_patients/analyze instead of the current ones. Should I put analyze as default here?

2023-09-06 15:15 UTC, Melkiades commented on R/utils_defaults_handling.R
> +  count_fraction_fixed_dp = format_count_fraction_fixed_dp,
also changed this name

2023-09-06 15:16 UTC, Melkiades commented on tests/testthat/test-summary_stats.R
>  testthat::test_that("summary_formats works as expected", {
This file can be removed eventually @edelarua

2023-09-06 18:05 UTC, Melkiades commented
After coming update, this will fix also https://github.com/insightsengineering/chevron/issues/618 and https://github.com/insightsengineering/sme-tasks/issues/639

2023-09-06 23:17 UTC, edelarua requested changes
Excellent job Davide! :) A couple of minor things in my review but I think the logic is all sound. I agree with your comments about removing `a_summary_internal` and the `type` argument which would require a bit more refactoring.

2023-09-06 23:17 UTC, edelarua commented on tests/testthat/_snaps/summarize_glm_count.md
> -      C: Combination 9.029759  6.295928  12.95068 C: Combination
Yeah my system always returns the updated values for this file but that breaks the integration tests which expect the current values so we always end up reverting to this version. It would be nice to fix this somehow

2023-09-06 23:17 UTC, edelarua commented on NEWS.md
> +* Added vectors of default formats and labels in `tern_default_formats` and `tern_default_labels`, respectively.
```suggestion
* Added vectors containing default statistic formats and labels as `tern_default_formats` and `tern_default_labels`, respectively.
```

2023-09-06 23:17 UTC, edelarua commented on NEWS.md
> +* Added utility to get methods from statistical method groups with `get_stats`.
```suggestion
* Added function `get_stats` to return methods from given statistical method groups.
```

2023-09-06 23:17 UTC, edelarua commented on NEWS.md
> +* Added utility to get formats `get_format_from_stats()` and labels `get_labels_from_stats()`.
```suggestion
* Added function `get_format_from_stats` to return formats and `get_labels_from_stats` to return labels for a given set of statistics.
```

2023-09-06 23:17 UTC, edelarua commented on R/utils_defaults_handling.R
> +assert_allowed_types <- function(type) {
```suggestion
assert_valid_types <- function(type) {
```

2023-09-06 23:17 UTC, edelarua commented on R/utils_defaults_handling.R
> +#' Defaults for stats methods names and their relative formats/labels
```suggestion
#' Defaults for statistical method names and their associated formats & labels
```

2023-09-06 23:17 UTC, edelarua commented on R/utils_defaults_handling.R
> +#' (`.stats`) and their relative formats (`.formats`) and labels (`.labels`). This utility
```suggestion
#' (`.stats`) and their associated formats (`.formats`) and labels (`.labels`). This utility
```

2023-09-06 23:17 UTC, edelarua commented on R/utils_defaults_handling.R
> +#' @param type (`character`) \cr type of data and result desired. Some stats defaults (and their formats and labels),
We usually don't put a space here, but I'm not sure if it actually makes a difference. I think you've added the space in all your new functions so you might want to change this in those as well.
```suggestion
#' @param stats (`character`)\cr statistical methods to get defaults formats for.
#' @param type (`character`)\cr type of data and result desired. Some stats defaults (and their formats and labels),
```

2023-09-06 23:17 UTC, edelarua commented on NEWS.md
> +* Statistical method for finding `p-value` in the discrete case is now termed `pval_counts`.
```suggestion
### Miscellaneous
* Grouped functions relating to valid method names and their default formats and labels into new source file `utils_defaults_handling.R`.
* Started deprecation of `summary_custom()` and `a_summary()` as a `S3` method.
* Renamed statistical method for `p-value` in the discrete case to `pval_counts`.
```

2023-09-07 10:43 UTC, Melkiades commented on R/analyze_variables.R
> +#'
@BFalquet if you want to give it a try this is the way

2023-09-07 10:45 UTC, Melkiades commented on R/summary_stats.R
>  summary_formats <- function(type = "numeric", include_pval = FALSE) {
now it is called `utils_default_stats_formats_labels.R`

2023-09-07 10:45 UTC, Melkiades commented on R/analyze_variables.R
> +a_summary <- function(x,
done

2023-09-07 10:47 UTC, Melkiades commented on R/utils_defaults_handling.R
> +  }
the only difference was in the label (and the method itself) so I think it is better to have them separate also in the statistics

2023-09-07 10:48 UTC, Melkiades commented on R/utils_defaults_handling.R
> +        "analyze_vars_numeric" = c(
that is very true. Should I make all of this internal?

2023-09-07 10:48 UTC, Melkiades commented on R/utils_defaults_handling.R
> +        "analyze_vars_numeric" = c(
I think it is still cool to use if you want to know the default stats

2023-09-07 10:50 UTC, Melkiades commented on R/utils_defaults_handling.R
> +  count_fraction_fixed_dp = format_count_fraction_fixed_dp,
@edelarua this is another change where for different functions (`count_occurrences` and `analyze_vars`) we use different standards. This is though a different thing so, as for pval I think it is better to have it expressed separately

2023-09-07 10:55 UTC, Melkiades commented on R/utils_defaults_handling.R
> +assert_allowed_types <- function(type) {
removed, as it was used only once

2023-09-07 15:48 UTC, Melkiades commented on R/utils_defaults_handling.R
> +    for (typ in type_loop) {
For the moment I took it out from the function `get_stats` and left it on the afun level. It is autodetermined but I think it is fine to keep them separate for this PR. We can eventually change this behavior in the future

2023-09-07 15:49 UTC, Melkiades commented on R/utils_defaults_handling.R
> +  }
w/o the type itself now it is simpler. I think it is fine to keep the "duplication"

2023-09-07 15:50 UTC, Melkiades commented on tests/testthat/_snaps/summarize_glm_count.md
> -      C: Combination 9.029759  6.295928  12.95068 C: Combination
should I revert these ?

2023-09-07 16:49 UTC, BFalquet commented on R/analyze_variables.R
> +#'
I can't believe it but it is actually working. congrats @Melkiades

2023-09-07 17:01 UTC, edelarua commented on R/utils_defaults_handling.R
> +  }
Sounds good!

2023-09-07 17:03 UTC, edelarua commented on tests/testthat/_snaps/summarize_glm_count.md
> -      C: Combination 9.029759  6.295928  12.95068 C: Combination
I would probably revert - in my experience it will probably break integration tests - but you could always merge and see what happens this time if you're curious

2023-09-07 17:20 UTC, edelarua requested changes
Looks great - everything is working for me! Just a few wording suggestions, and you should also rename the test file to match the renamed R file and then rerun tests.

2023-09-07 17:20 UTC, edelarua commented on R/argument_convention.R
> +#'   `"auto"` setting.
```suggestion
#' @param .formats (named `character` or `list`)\cr formats for the statistics. See Details in `analyze_vars` for more
#'   information on the `"auto"` setting.
```

2023-09-07 17:20 UTC, edelarua commented on R/utils_factor.R
> +#' @seealso [a_summary()] which uses this function as internal `afun` for [analyze_vars()].
```suggestion
#' @seealso [a_summary()] which uses this function internally.
```

2023-09-08 15:36 UTC, edelarua approved these changes
Good to go! Thanks Davide :)

2023-09-11 18:49 UTC, merged