Fix trailing "." when using `format_sigfig`
insightsengineering/tern pull request #1067
Opened 2023-09-21 20:23 UTC by edelarua

Closes #1066

2023-09-22 20:20 UTC, anajens commented on NEWS.md
> +* Fixed bug in `format_sigfig` causing some numbers to be printed with trailing "." character.
format_sigfig is new function so no need to capture this

2023-09-22 20:21 UTC, anajens approved these changes
Thanks @edelarua !

2023-09-25 09:48 UTC, Melkiades requested changes

2023-09-25 09:48 UTC, Melkiades commented on R/formatting_functions.R
> +    num <- gsub("\\.$", "", num) # remove trailing "."
I think this is not the best way to do this. Also, here there should be the possibility to have it fixed. I think flag adds the dot and g grounds. There is no need of signif function here from my testing. I would keep this as another option and remove the value value_paren and range as this is not yet needed and this will be a core function for the future. Composite functions can be added in a different way (by parsing and replacing) which is done in one of the formatting functions I have added. We can talk about this at the SU

2023-09-25 16:31 UTC, edelarua commented
Notes on implementation:
- Format `"fg"` is used to format using significant digits - `"f"` prints with fixed (non-scientific notation) format and `"g"` causes `digits` to represent number of significant digits (not decimal places).
- Without the `"#"` flag, additional required digits are not correctly added and leading whitespace is added instead. For example:
```
> formatC(signif(1.5, digits = 3), digits = 3, format = "fg", flag = "#")
[1] "1.50"
> formatC(signif(1.5, digits = 3), digits = 3, format = "fg")
[1] " 1.5"
```
- Without `sigfig` values are not rounded correctly. For example:
```
> formatC(signif(123123, digits = 3), digits = 3, format = "fg")
[1] "123000"
> formatC(123123, digits = 3, format = "fg")
[1] "123123"
```

2023-09-25 18:56 UTC, anajens requested changes
@edelarua this is looking a lot better but I think we need to be careful about which formats are supported. I suggest to either restrict the format list more explicitly and/or add more tests to verity that all formats in `list_valid_format_labels()` are supported:

Here's 2 cases to think about, both seem to be bugs in `format_value`:

(1) this gives an error:
```
num1 <- c(0.1239)
z <- format_sigfig(3, format = "xx%" )
z(num1)
>Error in x * 100 : non-numeric argument to binary operator
```

(2) This gives the wrong result "<0.0001"
```
num2 <- c(1234)
z <- format_sigfig(3, format = "x.xxxx | (<0.0001)" )
z(num2)
```

2023-09-25 19:31 UTC, anajens approved these changes
Thanks, this is much safer 😅

2023-09-25 19:33 UTC, merged