Adding Bland- Altman statistical function
insightsengineering/tern pull request #1135
Opened 2023-11-20 06:57 UTC by linc50

# Pull Request

I have added the Bland-Altman sfunction, which can be used to assess the agreement between two quantitative methods of measurement. Please kindly help to review the code.

Thanks,
Chanjuan

2023-11-20 07:05 UTC, linc50 commented
close issue #850

2023-11-20 11:02 UTC, Melkiades commented on tests/testthat/test-bland-altman.R
> +  x = rnorm(20)
Use `<-`

2023-11-20 11:03 UTC, Melkiades commented on tests/testthat/test-bland-altman.R
> +
not needed

2023-11-20 11:03 UTC, Melkiades commented on R/bland_altman.R
> +
not needed

2023-11-20 11:04 UTC, Melkiades commented on R/bland_altman.R
> +#' @param y ('numeric')\cr vector of numbers we want to analyze.
are you sure x is defined correctly in argument convention?

2023-11-20 11:04 UTC, Melkiades commented on R/bland_altman.R
> +#' @description 'r lifecycle::badge("stable")'
Description is not sufficient and it is missing connection with its main `rtables` uses

2023-11-20 11:05 UTC, Melkiades commented on R/bland_altman.R
> +#' @name s_bland_altman
I am not sure we need a dedicated file for this function, as we have already so many

2023-11-20 11:11 UTC, Melkiades requested changes
Thanks @linc50 for working on this :)

We need a NEWS entry, the documentation is not present (you need to roxygenize and add description and fix the reference), and we need to have this statistical function is some tabulation example, test and list of stats (see `get_stats`). I would also consider moving this to a file that has similar statistical functions as the name itself does necessarily cut it for a self-explanatory file. Remember to use the styler btw ;)

2023-11-20 11:12 UTC, Melkiades commented on R/bland_altman.R
> +# title={Statistical methods for assessing agreement between two methods of clinical measurement},
bibliography is handled in `tern` so to have bib refs in a dedicated file avoiding the style/linter exceptions and it is clearer to read. Search for the .bib file and its content to see how we accomplish this

2023-12-05 07:21 UTC, linc50 commented on R/bland_altman.R
> +#' @param y ('numeric')\cr vector of numbers we want to analyze.
yes, x is the vector we want to analyze, and to make it clear I added more description of parameter y.

2023-12-05 07:28 UTC, linc50 commented on R/bland_altman.R
> +#' @name s_bland_altman
Given there might be other functions applying bland altman method (for example,  bland altman plot), we'd better to keep this dedicated file for further development.

2023-12-05 07:58 UTC, linc50 commented on R/bland_altman.R
> +# title={Statistical methods for assessing agreement between two methods of clinical measurement},
have moved the bib information to REFERENCES.bib under tern

2023-12-05 08:09 UTC, linc50 commented on R/bland_altman.R
> +#' @description 'r lifecycle::badge("stable")'
added more information for description. And to be honest, this function does have little connection with rtables, shall we change the location of this function?

2023-12-20 15:12 UTC, Melkiades commented on R/bland_altman.R
> +  n <- length(n)                                      # number of 'observations'
`length(ind)` maybe?

2023-12-20 15:12 UTC, Melkiades commented on R/bland_altman.R
> +  if(n ==0){
```suggestion
  if(n == 0){
```

2023-12-20 15:29 UTC, Melkiades commented on R/bland_altman.R
> +#' @name s_bland_altman
We cannot have a dedicated file for every method only for further development. If its documentation and file remain stand-alone, no other will ever see or use it. I suggest adding it to some group of statistics/methods and adding links to it in the current documentation (remember to add it to pkgdown too)

2023-12-20 15:30 UTC, shajoezhu commented
Hi @Melkiades , we will update this PR with a g_bland_altman function

2023-12-20 15:31 UTC, Melkiades commented on R/bland_altman.R
> +#' @description 'r lifecycle::badge("stable")'
How do you use this function? Do you generate tables/plots with it?

2023-12-20 15:31 UTC, Melkiades commented on R/bland_altman.R
> +# title={Statistical methods for assessing agreement between two methods of clinical measurement},
I see it works, but maybe a direct ref when mentioned would be beneficial

2023-12-20 15:35 UTC, Melkiades commented
> Hi @Melkiades , we will update this PR with a g_bland_altman function

Ok super! so far, I think we have used the main user-facing (tables/plot) functions to name and direct files' content. I would probably wait to have the plot function and name it as you suggested, `g_bland_altman`. We can always refactor stats and methods to have a different semantic grouping at a later time (also after Daniels' work maybe?)

2024-01-04 09:02 UTC, pawelru commented on R/bland_altman.R
> +  if(n ==0){
please have a look at the pre-commit tool that will does that for you automatically on commit

2024-01-18 09:40 UTC, pawelru commented on tests/testthat/test-bland-altman.R
> +testthat::test_that("works correctly", {
Can you please enhance test description. This doesn't tell you much :) 
Note that these descriptions are visible on a package level when running tests for the whole package.

2024-01-22 02:06 UTC, shajoezhu approved these changes
lgtm! hey @Melkiades , I was wondering if you would want to take another look, Thanks

2024-01-22 09:11 UTC, Melkiades reviewed
@shajoezhu, we can proceed with this, but I would appreciate a little clarification. There is no primary `a_bland_altman` function or some rtables-related function. I understand this could be part of a plan to add statistical functions for other packages or for other uses. If this is the case, I suggest we group them in a file (e.g. `general_stats` or `external_stats`) where we specify that they are for external uses; I expect more functions will gather there.

On the technical side, it is missing the function references in pkgdown and needs the plot function test.

2024-01-22 15:34 UTC, Melkiades commented
> > @shajoezhu, we can proceed with this, but I would appreciate a little clarification. There is no primary `a_bland_altman` function or some rtables-related function. I understand this could be part of a plan to add statistical functions for other packages or for other uses. If this is the case, I suggest we group them in a file (e.g. `general_stats` or `external_stats`) where we specify that they are for external uses; I expect more functions will gather there.
> > On the technical side, it is missing the function references in pkgdown and needs the plot function test.
> 
> Thanks @Melkiades , I created an issue #1175 to follow up on the ggplot test, let's do this after we resolve the svg plot testing issue.
Thanks 👍 
> 
> the s_ function was dedicated for supporting the plot, there is no need for table at this moment, we had looked up on the standard before, and there was no example there.
I see, then LGTM! 👍 
> 
> I thought g_ pattern should allow us to add this to pkgdown site, correct me if I was wrong. probably no need to duplicate materials on the s_bland_altman function. thanks
Good point. It is true ^^, hence the absence of error in ci/cd

2024-01-22 15:35 UTC, Melkiades approved these changes
LGTM! Thanks for working on this ;)

2024-01-22 15:38 UTC, merged