add snaps for bland-altman function
insightsengineering/tern pull request #1201
Opened 2024-03-07 21:25 UTC by ayogasekaram

closes #1175

2024-03-08 02:07 UTC, shajoezhu commented on tests/testthat/test-bland-altman.R
> +  y <- rnorm(20)
hi @ayogasekaram , 20 numbers is not too much. i think we can include in the code to avoid using random number generations

2024-03-08 02:07 UTC, shajoezhu commented on tests/testthat/test-bland-altman.R
> +  y <- rnorm(20)
hi @ayogasekaram , 20 numbers is not too much. i think we can include in the code to avoid using random number generations

2024-03-08 02:08 UTC, shajoezhu requested changes
use fixed numbers, avoid regenerating numbers

2024-03-08 02:09 UTC, shajoezhu requested changes
and updates, after https://github.com/insightsengineering/tern/pull/1200/files merged

2024-03-08 11:22 UTC, Melkiades reviewed
@ayogasekaram thanks for this! Just one note for me: we should skip graph testing on ci for now right? And also is it calling nestcolor? I think I forgot to enforce it when reviewing original PR

2024-03-08 15:03 UTC, ayogasekaram commented
@Melkiades great point. the `g_bland_altman` function only calls base colours - not the nestcolors package. The `with_options` is setup for this test like the other graphs so I think it should be okay but I can remove it if it fails the integration tests :)

2024-03-11 03:09 UTC, shajoezhu approved these changes
lgtm! Thanks @ayogasekaram

2024-03-11 13:12 UTC, merged