Refactor `summarize_change()`
insightsengineering/tern pull request #1347
Opened 2024-11-04 15:13 UTC by Melkiades

Fixes #1345

2024-11-04 15:14 UTC, Melkiades commented on R/summarize_change.R
>    )
we can add alt_df handling to the whole stack

2024-11-04 15:15 UTC, Melkiades commented on R/summarize_change.R
> +  checkmate::assert_string(vars)
not fully necessary as with get_additional_analysis_fun_parameters() we get `.var`

2024-11-04 15:22 UTC, Melkiades commented on vignettes/tern_functions_guide.Rmd
> +Level 2: `a_change_from_baseline()`: all parameters starting with a dot `.` are used. Mainly `.stats`, `.formats`, `.labels`, and `.indent_mods` are used. We also add `extra_afun_params` to the `...`
needs refinement

2024-11-05 09:07 UTC, pawelru commented
There is a bug in R CMD CHECK workflow logic. Sorry about that. There is a PR to fix it: https://github.com/insightsengineering/r.pkg.template/pull/261

2024-11-05 16:43 UTC, Melkiades commented
@pawelru this is the current error:
! Failed to render 'vignettes/tern_functions_guide.Rmd'.
✖ Quitting from lines 65-87 [unnamed-chunk-3] (tern_functions_guide.Rmd)
Caused by error:
! could not find function "get_additional_analysis_fun_parameters"

In the vignette this function is not present though. Am I missing something obvious?

2024-11-06 01:19 UTC, shajoezhu commented on R/utils_rtables.R
> +get_additional_afun_params <- function(add_alt_df = FALSE) {
get_additional_analysis_fun_parameters

get_additional_afun_params?

2024-11-06 01:20 UTC, shajoezhu commented on R/utils_rtables.R
> +get_additional_afun_params <- function(add_alt_df = FALSE) {
perhaps lets just use get_additional_afun_params

2024-11-06 01:20 UTC, shajoezhu commented on R/summarize_change.R
> +  extra_args[[".additional_fun_parameters"]] <- get_additional_analysis_fun_parameters(add_alt_df = FALSE)
get_additional_afun_params

2024-11-06 01:21 UTC, shajoezhu commented
> @pawelru this is the current error:
> 
> ```
> 
> ! Failed to render 'vignettes/tern_functions_guide.Rmd'.
> ✖ Quitting from lines 65-87 [unnamed-chunk-3] (tern_functions_guide.Rmd)
> Caused by error:
> ! could not find function "get_additional_analysis_fun_parameters"
> ```
> 
> In the vignette this function is not present though. Am I missing something obvious?

it's the function name @Melkiades

2024-11-06 02:54 UTC, shajoezhu commented
Error applying analysis function (var - CHG): could not find function ".split_default_from_custom_stats"
	occured at (row) path: AVISIT[Baseline]

2024-11-06 03:02 UTC, shajoezhu commented
hi @Melkiades , can you please update the DESCRIPTION file

```diff
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -144,6 +144,8 @@ Collate:
     'h_survival_duration_subgroups.R'
     'imputation_rule.R'
     'incidence_rate.R'
+    'individual_patient_plot.R'
+    'kaplan_meier_plot.R'
     'logistic_regression.R'
     'missing_data.R'
     'odds_ratio.R'
@@ -166,6 +168,7 @@ Collate:
     'summarize_glm_count.R'
     'summarize_num_patients.R'
     'summarize_patients_exposure_in_cols.R'
+    'summarize_variables.R'
```

and rerun roxygen

2024-11-06 10:32 UTC, Melkiades commented on R/utils_rtables.R
> +get_additional_afun_params <- function(add_alt_df = FALSE) {
it was the longer version but it is too long for lintr

2024-11-06 10:34 UTC, Melkiades commented on R/utils_rtables.R
> +get_additional_afun_params <- function(add_alt_df = FALSE) {
thanks

2024-11-06 10:45 UTC, Melkiades commented
> hi @Melkiades , can you please update the DESCRIPTION file
> 
> ```diff
> --- a/DESCRIPTION
> +++ b/DESCRIPTION
> @@ -144,6 +144,8 @@ Collate:
>      'h_survival_duration_subgroups.R'
>      'imputation_rule.R'
>      'incidence_rate.R'
> +    'individual_patient_plot.R'
> +    'kaplan_meier_plot.R'
>      'logistic_regression.R'
>      'missing_data.R'
>      'odds_ratio.R'
> @@ -166,6 +168,7 @@ Collate:
>      'summarize_glm_count.R'
>      'summarize_num_patients.R'
>      'summarize_patients_exposure_in_cols.R'
> +    'summarize_variables.R'
> ```
> 
> and rerun roxygen

`roxygen2::update.collate(".")` does not apply any modifications in my local (there should not be any difference in source files afaik)

2024-11-06 23:01 UTC, shajoezhu requested changes
hi @Melkiades , the CI test is still not passing

can you take another look. thanks!

```
a_change_from_baseline: no visible binding for global variable
  ‘.df_row’
a_change_from_baseline: no visible binding for global variable ‘.var’
get_additional_afun_params: missing arguments not allowed in calls to
  ‘c’
Undefined global functions or variables:
  .df_row .var
```

2024-11-06 23:03 UTC, shajoezhu commented
> > hi @Melkiades , can you please update the DESCRIPTION file
> > ```diff
> > --- a/DESCRIPTION
> > +++ b/DESCRIPTION
> > @@ -144,6 +144,8 @@ Collate:
> >      'h_survival_duration_subgroups.R'
> >      'imputation_rule.R'
> >      'incidence_rate.R'
> > +    'individual_patient_plot.R'
> > +    'kaplan_meier_plot.R'
> >      'logistic_regression.R'
> >      'missing_data.R'
> >      'odds_ratio.R'
> > @@ -166,6 +168,7 @@ Collate:
> >      'summarize_glm_count.R'
> >      'summarize_num_patients.R'
> >      'summarize_patients_exposure_in_cols.R'
> > +    'summarize_variables.R'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and rerun roxygen
> 
> `roxygen2::update.collate(".")` does not apply any modifications in my local (there should not be any difference in source files afaik)

weired. when I run locally, these get added, and after that, more document rd files get rendered.

2024-11-07 02:15 UTC, shajoezhu commented
> > hi @Melkiades , can you please update the DESCRIPTION file
> > ```diff
> > --- a/DESCRIPTION
> > +++ b/DESCRIPTION
> > @@ -144,6 +144,8 @@ Collate:
> >      'h_survival_duration_subgroups.R'
> >      'imputation_rule.R'
> >      'incidence_rate.R'
> > +    'individual_patient_plot.R'
> > +    'kaplan_meier_plot.R'
> >      'logistic_regression.R'
> >      'missing_data.R'
> >      'odds_ratio.R'
> > @@ -166,6 +168,7 @@ Collate:
> >      'summarize_glm_count.R'
> >      'summarize_num_patients.R'
> >      'summarize_patients_exposure_in_cols.R'
> > +    'summarize_variables.R'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and rerun roxygen
> 
> `roxygen2::update.collate(".")` does not apply any modifications in my local (there should not be any difference in source files afaik)

I think I know why now. I use `devtools::document(roclets = c('rd', 'collate', 'namespace'))`

2024-11-07 02:45 UTC, shajoezhu commented
downstream works ok https://github.com/insightsengineering/scda.test/pull/161/files

2024-11-07 18:48 UTC, Melkiades commented
> roxygen2::update_collate(".")

I do have that version but those files are not present in R/

2024-11-07 21:48 UTC, shajoezhu approved these changes
lgtm! Thanks @Melkiades

2024-11-07 21:48 UTC, merged