Refactoring of `analyze_vars` with specifics for .stat_names
insightsengineering/tern pull request #1361
Opened 2024-12-11 14:14 UTC by Melkiades

# Pull Request

Fixes #1352

2024-12-12 16:48 UTC, Melkiades commented on tests/testthat/_snaps/analyze_variables.md
> -      1                           n           5.00         -1 number of records
to investigate

2024-12-12 16:49 UTC, Melkiades commented on tests/testthat/_snaps/analyze_variables.md
> +      Mean (SD)   2.5 (1.3)
It should be NAs

2024-12-12 16:49 UTC, Melkiades commented on tests/testthat/_snaps/analyze_variables.md
> -      NA   2 (40%)
Lost NA

2024-12-12 16:50 UTC, Melkiades commented on tests/testthat/_snaps/analyze_variables.md
> +      2              sum               48.7          0                         Sum
Why this calc changed?

2024-12-19 23:17 UTC, Melkiades commented on tests/testthat/_snaps/analyze_variables.md
> -      1                           n           5.00         -1 number of records
Solved in last commits

2024-12-19 23:19 UTC, Melkiades commented on R/utils_default_stats_formats_labels.R
> +      nm_of_levs <- levels_per_stats[[stat_i]]
to comment better

2024-12-19 23:21 UTC, Melkiades commented on R/utils_factor.R
> +#' @return A `list` with modified elements `stat_out`, `.formats`, `.labels`, `.levels`, and `.indent_mods`.
to fix: ungroup_stats should be removed in favor of get_*_from_stats

2024-12-19 23:22 UTC, Melkiades commented on R/utils_factor.R
> -  if (empty_pval_counts) x[["pval_counts"]] <- character()
these are if pval is NULL?

2024-12-19 23:24 UTC, Melkiades commented on tests/testthat/_snaps/analyze_variables.md
> -      NA      2 (40%)
lost NA

2024-12-26 17:13 UTC, Melkiades commented on R/analyze_variables.R
> +  if (na_rm) {
na_rm can be reverted into na.rm if you think it is just creating issues downstream

2024-12-26 17:13 UTC, Melkiades commented on R/analyze_variables.R
> +  if (isTRUE(compare_with_ref_group)) {
compare functions have been deprecated and merged in here

2024-12-26 17:15 UTC, Melkiades commented on R/analyze_variables.R
> +  y$n_blq <- list("n_blq" = c("n_blq" = sum(grepl("BLQ|LTR|<[1-9]|<PCLLOQ", x))))
useful to `get_stat_names`

2024-12-26 17:16 UTC, Melkiades commented on R/analyze_variables.R
> +  default_and_custom_stats_list <- .split_std_from_custom_stats(.stats)
it is possible to add custom stats

2024-12-26 17:16 UTC, Melkiades commented on R/analyze_variables.R
> -                      compare = FALSE,
all these vars are broadcasted from analyze

2024-12-26 17:17 UTC, Melkiades commented on R/analyze_variables.R
> +  .stat_names <- get_stat_names(x_stats, .stat_names_in) # note is x_stats
core stat_names modification

2024-12-26 17:18 UTC, Melkiades commented on R/riskdiff.R
> +    } else if (is.list(s_x[[stat]]) && !is.null(names(s_x[[stat]]))) {
now statistics are character vectors

2024-12-26 17:18 UTC, Melkiades commented on R/riskdiff.R
> +    } else if (is.list(s_x[[stat]]) && !is.null(names(s_x[[stat]]))) {
*named numeric vectors

2024-12-26 17:19 UTC, Melkiades commented on R/utils_default_stats_formats_labels.R
> +.adjust_stats_desc_by_in_def <- function(levels_per_stats, user_in, tern_defaults) {
This is only to be extra sure that you can change the labels in anyway you want (to do add this for formats and indentation)

2024-12-26 17:20 UTC, Melkiades commented on R/utils_factor.R
> -  if (empty_pval_counts) x[["pval_counts"]] <- character()
pval handling to be refactored

2024-12-26 17:21 UTC, Melkiades commented on tests/testthat/_snaps/analyze_variables.md
> +      2              sum               48.7          0                         Sum
still no idea

2024-12-26 17:21 UTC, Melkiades commented on tests/testthat/_snaps/analyze_variables.md
> -      2 median_ci   -0.41 - 1.10          3 Median 95% CI
why changed?

2025-01-10 00:03 UTC, edelarua requested changes
This looks great!! Just a few comments from me regarding some improvements that could be made to the documentation, but the code all seems good!

2025-01-13 06:07 UTC, shajoezhu commented
```
> a_summary(
+   factor(c("a", "a", "b", "c", "a")),
+   .ref_group = factor(c("a", "a", "b", "c")), compare_with_ref_group = TRUE
+ )
Error in s_summary.factor(x = c(1L, 1L, 2L, 3L, 1L), .ref_group = c(1L,  : 
  Assertion on '.in_ref_col' failed: Must be of type 'logical flag', not 'NULL'.
Calls: a_summary ... s_summary.factor -> <Anonymous> -> makeAssertion -> mstop
```

2025-01-13 06:29 UTC, shajoezhu requested changes
```
Error in s_count_patients_with_event(tern_ex_adae, .var = "SUBJID", filters = c(TRTEMFL = "Y")) : 
     argument ".N_col" is missing, with no default
   Calls: s_count_patients_with_event ... s_count_values.character -> s_summary -> s_summary.logical
```

2025-01-15 23:38 UTC, edelarua commented on tests/testthat/_snaps/analyze_variables.md
> -      2 median_ci   -0.41 - 1.10          3 Median 95% CI
I think this is just a random seed difference

2025-01-15 23:39 UTC, edelarua commented on tests/testthat/_snaps/analyze_variables.md
> +      2              sum               48.7          0                         Sum
I think this is just a random seed difference

2025-01-15 23:41 UTC, edelarua commented
@shajoezhu I think all of the issues with this PR have been fixed. I'm not sure why but the Pkgdown Docs check always seems to take longer to update its package dependencies, which I think is why this check still isn't passing.

2025-01-16 03:30 UTC, shajoezhu commented on R/utils_factor.R
> -  if (empty_pval_counts) x[["pval_counts"]] <- character()
let's do it in another PR

2025-01-16 03:30 UTC, shajoezhu approved these changes
this is brilliant work! Thanks a lot @Melkiades @edelarua

2025-01-16 03:34 UTC, merged

2025-01-20 14:30 UTC, Melkiades commented on R/analyze_variables.R
> +    inclNAs = !na_rm,
eheh this silly mistake got on my nerves! nice catch

2025-01-20 14:31 UTC, Melkiades commented on R/analyze_variables.R
> +    inclNAs = !na_rm,
I noticed there are different ways to handle NAs in each statistical function. What should we do about this? Keep NAs until the last statistical level and then do separate things or take them out here? @edelarua @shajoezhu

2025-01-20 14:36 UTC, Melkiades commented on R/analyze_variables.R
> +  if (na_rm) {
I agree 100%. Lets keep it rolling 👍

2025-01-20 14:36 UTC, Melkiades commented on R/analyze_variables.R
> +s_summary <- function(x, denom, control, ...) {
I agree!

2025-01-20 14:37 UTC, Melkiades commented on R/analyze_variables.R
> +s_summary.logical <- function(x, denom = c("n", "N_col", "N_row"), ...) {
I might have lost track of this one

2025-01-20 14:39 UTC, Melkiades commented on R/utils_factor.R
> -  if (empty_pval_counts) x[["pval_counts"]] <- character()
I agree

2025-01-20 16:35 UTC, shajoezhu commented on R/analyze_variables.R
> +    inclNAs = !na_rm,
lets fix this in new version. agree