597 only checkmate@main
insightsengineering/tern pull request #600
Opened 2022-06-22 10:10 UTC by Melkiades

# Pull Request

Fixes #597

2022-06-22 11:45 UTC, kpagacz commented on NEWS.md
> +  `checkmate::assert_integerish()` and made internal
Have you considered a deprecation strategy here? CoreDev usually deprecates a function for at least one release cycle before completely removing it https://lifecycle.r-lib.org/articles/stages.html See https://github.com/insightsengineering/teal/blob/53a9ae7f670424b6bedd9a1437b435a1dcbdf2a1/R/init.R#L236-L240

2022-06-22 12:09 UTC, kpagacz reviewed
The issue proposes refactoring all `assertthat` calls from `tern`. I see `assertthat` calls in this PR left out. Is this on purpose?

2022-06-22 15:24 UTC, Melkiades commented on NEWS.md
> +  `checkmate::assert_integerish()` and made internal
I agree with this and I am aware of this. There are files in tern called deprecated since a couple of releases. I think we can remove them during this increment, right @shajoezhu?

2022-06-22 15:26 UTC, Melkiades commented on R/utils_checkmate.R
>  }
I can also do a shallow replacement of `checkmate` instead of `assertthat` if you think it is better. Also, the opposite would be faster and easier, with the exception that the latter is not maintained and it does not provide a stable release since 2019 (see issue #597)

2022-06-24 08:29 UTC, shajoezhu commented on R/abnormal_by_worst_grade.R
> +  assert_valid_factor(df[[variables$param]])
need to assert names of variables

2022-06-24 08:34 UTC, shajoezhu commented on R/utils_checkmate.R
> +#' # tern:::assert_list_of_variables(list("bla" = 2))
remove comment?

2022-06-24 08:35 UTC, shajoezhu commented on R/utils_checkmate.R
> +#' # tern:::assert_list_of_variables(list("bla" = 2))
# failures ?

2022-06-24 08:36 UTC, shajoezhu requested changes
Hi @Melkiades , looks really good. some minor request for changes, see comments

2022-06-24 08:37 UTC, Melkiades commented on R/abnormal_by_worst_grade.R
> +  assert_valid_factor(df[[variables$param]])
These are the complete lines from the file:
```{r}
  checkmate::assert_string(.var)
  assert_valid_factor(df[[.var]])
  assert_valid_factor(df[[variables$param]])
  assert_valid_factor(df[[variables$grade_dir]])
  assert_df_with_variables(df, c(a = .var, variables))
  assert_character_or_factor(df[[variables$id]])
```

2022-06-24 08:39 UTC, Melkiades commented on R/utils_checkmate.R
> +#' # tern:::assert_list_of_variables(list("bla" = 2))
so these are error checks and assert_* throws out an error. Usually, these functions are internal with no examples and only tests, but I kept the examples with the comment. What do you think is better to do?

2022-06-24 08:39 UTC, shajoezhu commented on R/abnormal_by_worst_grade.R
> +  assert_df_with_variables(df, c(a = .var, variables))
my bad, i missed this line

2022-06-24 08:41 UTC, shajoezhu commented on R/utils_checkmate.R
> +#' # tern:::assert_list_of_variables(list(1, 2))
```suggestion
#' # failures
#' # tern:::assert_list_of_variables(list(1, 2))
```

2022-06-24 08:45 UTC, kpagacz commented
Some assertions from assertthat are still left :(

2022-06-24 08:56 UTC, Melkiades commented
> Some assertions from assertthat are still left :(

Joe proposed to divide it into incremental PRs

2022-06-24 10:12 UTC, merged