removing assert_factor_or_character
insightsengineering/tern pull request #603
Opened 2022-06-24 11:12 UTC by Melkiades

# Pull Request

Fixes #602

2022-06-24 12:25 UTC, edelarua approved these changes
LGTM @Melkiades!

2022-06-26 22:15 UTC, shajoezhu requested changes
Thanks @Melkiades and @edelarua for looking into this. checks are failing. please update with

```
roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace'))
```

2022-06-27 14:57 UTC, gogonzo commented on R/h_survival_duration_subgroups.R
> +  if (!is.null(variables$subgroups)) checkmate::assert_character(variables$subgroups)
```suggestion
  checkmate::assert_character(variables$subgroups, null.ok = TRUE)
```

2022-06-27 14:59 UTC, gogonzo commented on R/logistic_regression.R
> +  checkmate::assertMultiClass(terms, classes = c("factor", "character"))
just to be consistent by using snake_case only
```suggestion
  checkmate::assert_multi_class(terms, classes = c("factor", "character"))
```

2022-06-27 14:59 UTC, Melkiades commented on R/h_survival_duration_subgroups.R
> +  if (!is.null(variables$subgroups)) checkmate::assert_character(variables$subgroups)
thanks for this! I did not know you could do it this way. I will fix it where needed

2022-06-27 16:07 UTC, Melkiades commented on R/h_survival_duration_subgroups.R
> +  if (!is.null(variables$subgroups)) checkmate::assert_character(variables$subgroups)
I think this can be another issue for the future as there are many of these in the package and this PR is already huge (I will do it in the cases

2022-06-27 16:07 UTC, Melkiades commented on R/logistic_regression.R
> +  checkmate::assertMultiClass(terms, classes = c("factor", "character"))
done in the next commit! thanks.

2022-06-28 15:19 UTC, shajoezhu commented on DESCRIPTION
> -    assertthat,
🥇

2022-06-29 06:28 UTC, shajoezhu commented on R/control_step.R
> +  checkmate::assert_int(num_points, lower = 2)
use `na.ok` to check missing?

2022-06-29 06:33 UTC, shajoezhu commented on R/summarize_variables.R
> +  checkmate::assert_true(length(quantiles) == 2)
we have different implementation here for checking the length here

2022-06-29 06:37 UTC, shajoezhu commented on R/h_map_for_count_abnormal.R
> +  checkmate::assert_int(length(normal_value), lower = 1, upper = 1)
we have a different implmentation using assert_true in this PR as well

2022-06-29 06:50 UTC, shajoezhu commented on R/h_step.R
> +  checkmate::assert_int(length(arm_lvls), lower = 2, upper = 2)
different implmentation in the same PR

2022-06-29 06:51 UTC, shajoezhu commented on R/logistic_regression.R
> +    checkmate::assert_set_equal(fit_glm$family$family, "binomial")
what about to use assert_true

2022-06-29 06:55 UTC, shajoezhu commented on _pkgdown.yml
> -      - assert_df_with_factors
keep this one?

2022-06-29 06:59 UTC, shajoezhu commented on NEWS.md
> +* `assert_df_with_factors`, `assert_equal_length`, and `assert_proportion_value`
perhaps we should start a new util package to check these assertions, will be widely useful in other project as well. and we can export them

2022-06-29 07:41 UTC, Melkiades commented on NEWS.md
> +* `assert_df_with_factors`, `assert_equal_length`, and `assert_proportion_value`
I think this would be perfectly fine in a utils' package. I would not create a package for assertions (it is only 200 lines) and it is not used downstream by any other package

2022-06-29 07:44 UTC, Melkiades commented on R/logistic_regression.R
> +    checkmate::assert_set_equal(fit_glm$family$family, "binomial")
I adopted assert_set_equal because I think it is a bit more informative and it is possibly a better comparison method than `==`, but I do not know if it actually matters. It is possible to use assert_true ofc.

2022-06-29 07:47 UTC, Melkiades commented on R/h_map_for_count_abnormal.R
> +  checkmate::assert_int(length(normal_value), lower = 1, upper = 1)
yes, this is the most informative and I would keep this.

2022-06-29 07:48 UTC, Melkiades commented on R/h_step.R
> +  checkmate::assert_int(length(arm_lvls), lower = 2, upper = 2)
Similarly keeping this as standard for length checks

2022-06-29 07:49 UTC, Melkiades commented on _pkgdown.yml
> -      - assert_df_with_factors
it is not used downstream nor in the catalogues, only internally

2022-06-29 07:50 UTC, Melkiades commented on R/control_step.R
> +  checkmate::assert_int(num_points, lower = 2)
in assert_int the default for na.ok is FALSE

2022-06-29 07:51 UTC, Melkiades commented on R/summarize_variables.R
> +  checkmate::assert_true(length(quantiles) == 2)
I will apply the other implementation (next commit)

2022-06-29 07:53 UTC, Melkiades commented on R/summarize_variables.R
> +  checkmate::assert_true(length(quantiles) == 2)
what do you think about these?
`checkmate::assert_true(length(strata_data) == nrow(df_tte))`

2022-06-29 09:34 UTC, shajoezhu approved these changes
lgtm! Many thanks @Melkiades

2022-06-29 09:34 UTC, merged