393 Clean up pkgdown site documentation
insightsengineering/tern pull request #610
Opened 2022-06-28 16:03 UTC by edelarua

Closes #393

2022-06-29 10:38 UTC, Melkiades commented on R/compare_variables.R
> +#' @description Constructor function which creates a combined Formatted Analysis function for use in
missing badge

2022-06-29 10:41 UTC, Melkiades commented on R/compare_variables.R
> +#' Constructor Function for [compare_vars()]
If this is not described in the same document of compare_variables, it should be in a separate file. But as this is internal, Should it stay in that description doc? (I genuinely do not know this)

2022-06-29 10:47 UTC, Melkiades commented on R/count_cumulative.R
> +#' Helper Function for [s_count_cumulative()]
similar if not @ describeIn should have a separate file (also to match the documentation files).

2022-06-29 10:51 UTC, Melkiades requested changes
In general great improvement! Just I think that many of the `@describeIn` should be reinstated as not doing so would put them in a separate doc file which in the case of internals is not reachable if not with `tern:::`

2022-06-29 10:57 UTC, Melkiades commented on R/cox_regression.R
> +#' Fits for Cox Proportional Hazards Regression
I would split this file again in two because having two `#' @name` in one file can be very chaotic (you do not know where the source file is). So I would add a file called fit_coxreg with that (we can do this in another issue np)

2022-06-29 10:59 UTC, Melkiades commented on R/g_step.R
> -#' @describeIn g_step Custom Tidy Method for STEP Results
also here the `@describeIn` may be necessary

2022-06-29 11:03 UTC, Melkiades commented on _pkgdown.yml
> +    desc: |
typo

2022-06-29 11:56 UTC, edelarua commented
Hi @shajoezhu, in the pkgdown Reference section functions are grouped by their .Rd file so I moved several to their own .Rd files to avoid grouping functions we don't want together.

Can you weigh in on whether we would should create separate .R files corresponding to each separate .Rd file or prefer to keep number of .R files to a minimum by grouping .Rd files of like functions within the same .R files (as was previously done with some h_ and d_ functions)?

2022-11-10 11:12 UTC, Melkiades commented
I think we may close this as it would be really too much work to merge with main atm. What do you think @edelarua?

2022-11-10 12:35 UTC, edelarua commented
> I think we may close this as it would be really too much work to merge with main atm. What do you think @edelarua?

I agree - it will be much easier to just create a new PR at this point. I'll close this PR.

2022-11-10 12:35 UTC, closed without merging