generating log-rank p value by survdiff
insightsengineering/tern pull request #639
Opened 2022-07-14 09:11 UTC by JiaLiu0001

close #611

2022-07-15 06:38 UTC, shajoezhu requested changes
Thanks for the changes @JiaLiu0001 , could you add test case for this as well. Many thanks!

2022-07-18 03:05 UTC, JiaLiu0001 commented
> Thanks for the changes @JiaLiu0001 , could you add test case for this as well. Many thanks!

Hi Joe, thank you for the comment. The test case for this issue is updated, please let me know if there's any further comment.

2022-07-19 03:07 UTC, shajoezhu approved these changes
Hi @JiaLiu0001 , very nice! thanks for the change. I am approving this PR now. Once you fix the spelling issue it is good to go. Thanks!

```
Run insightsengineering/r-spellcheck-action@v2
Run options(repos = c(CRAN = "https://cloud.r-project.org/"))
Loading required package: spelling
Run cd .
  WORD  FOUND IN
ph   NEWS.md:6[5](https://github.com/insightsengineering/tern/runs/7401668373?check_suite_focus=true#step:4:6)
Number of misspelled words: 1
You may correct the spellings of the words above or add them to the "inst/WORDLIST" file by running spelling::update_wordlist()
Error: Process completed with exit code 1.
```

2022-07-19 04:24 UTC, merged

2023-01-11 06:33 UTC, clarkliming commented on R/survival_coxph_pairwise.R
> +  log_rank_pvalue <- 1 - pchisq(orginal_survdiff$chisq, length(orginal_survdiff$n) - 1)
@JiaLiu0001 I think we should use `pchisq(lower.tail = FALSE)` instead of `1 - pchisq`. The former is accurate; although we don't have differences in printed out version (always <0.001 in both method)