620 wald correction update@main
insightsengineering/tern pull request #641
Opened 2022-07-14 13:26 UTC by ayogasekaram

# Pull Request

Replacing stats::proptest with DescTools equivalent BinomDiffCI for wald's test and correction.

Fixes #620

2022-07-15 06:40 UTC, shajoezhu requested changes
Hi @ayogasekaram , many thanks for this change. Can you please add test case for this well. thanks!

2022-07-15 08:59 UTC, pawelru commented on R/prop_diff.R
> +  if (correct == TRUE) {
protip: `isTRUE()`

```
> x <- TRUE
> isTRUE(x)
[1] TRUE
> x == TRUE
[1] TRUE
> x <- iris
> isTRUE(x)
[1] FALSE
> x == TRUE
       Sepal.Length Sepal.Width Petal.Length Petal.Width Species
  [1,]        FALSE       FALSE        FALSE       FALSE   FALSE
  [2,]        FALSE       FALSE        FALSE       FALSE   FALSE
(...)
```

2022-07-20 09:46 UTC, Melkiades approved these changes
Lgtm! I was just wondering how big is `DescTools` as new dep?

2022-07-21 00:30 UTC, shajoezhu commented
> Lgtm! I was just wondering how big is `DescTools` as new dep?

DescTools is quite nice, and I think it will help us a lot, many things we can learn from the package, howeverI am inclined not to include DescTools as dependency into our package, as it is also going through development. some stats are right for some minor versions, but not in others. we need to do some investigation on this.

2022-08-08 10:06 UTC, shajoezhu commented on tests/testthat/test-table_rspt01.R
> +      "", "-11.9", "(0.2, 23.7)", "0.0416", "0.57 (0.34 - 0.96)",
@ayogasekaram , can you check this please, seems this confidence interval have different sign, and the pointer estimator falls out side?

2022-08-08 10:07 UTC, shajoezhu requested changes
Hi @ayogasekaram , just want to double check the sign's of the CIs. thanks

2022-08-10 02:50 UTC, shajoezhu commented on R/desctool_binom_diff.R
> +        w1 <- DescTools::BinomCI(
Hey @ayogasekaram , I was hoping we could use `DescTools_BinomCI` for this

2022-08-10 02:50 UTC, shajoezhu requested changes
use `DescTools_BinomCI`

2022-08-10 02:52 UTC, shajoezhu commented on DESCRIPTION
> +    DescTools,
let's not introduce this package into the dependency,

2022-08-11 04:55 UTC, shajoezhu requested changes
Hi Abi, many thanks for the changes. I have reviewed, and we will need to update the sign for the numbers. I will explain more in details via email.

2022-08-11 05:32 UTC, shajoezhu commented on R/prop_diff.R
> +      tbl[1], sum(tbl[1], tbl[3]),
Might need to change the order here

2022-08-11 14:51 UTC, shajoezhu approved these changes
awesome! Thanks so much @ayogasekaram

2022-08-11 14:52 UTC, shajoezhu commented
Thanks so much @ayogasekaram . I have approved this PR, once the conflict is resolved. we can merge this back in!

2022-08-11 23:29 UTC, shajoezhu commented
Hi @ayogasekaram , the check is still failing, can you take another look please. Thanks!

2022-08-12 15:04 UTC, merged

2022-08-17 03:12 UTC, cicdguy commented
Ah shucks. This branch was called `620_wald_correction_update@main` instead of `620_wald_correction_update@pre-release`, and this is causing issues with the `tern` release with tests failing here: https://github.com/insightsengineering/tern/pull/682

@shajoezhu This is a release blocker. We need to get this resolved.