711 Add footnotes parameter to `g_km`
insightsengineering/tern pull request #714
Opened 2022-09-27 18:12 UTC by edelarua

Closes #711

2022-09-27 23:14 UTC, shajoezhu requested changes
replace code repetition with a new helper function

2022-09-27 23:14 UTC, shajoezhu commented on R/kaplan_meier_plot.R
> +        )
Hi @edelarua , it seems that we have a lot of repetition here. can you create a small helper function for this please. Thanks

2022-09-28 12:01 UTC, edelarua commented on R/kaplan_meier_plot.R
> +        )
Good idea! I have cleaned up the code in this section so there's no repetition.

2022-09-28 13:49 UTC, shajoezhu approved these changes
lgtm! Thanks @edelarua very neat!

2022-09-28 13:50 UTC, merged