401 add rate01 tlg@main
insightsengineering/tern pull request #739
Opened 2022-11-09 19:07 UTC by ayogasekaram

added unit tests for summarize_glm_count

adding rate01 to tlg MR found here: https://code.roche.com/nest/docs/tlg-catalog/devel/-/merge_requests/162

closes #538

2022-11-10 08:09 UTC, shajoezhu commented on R/summarize_glm_count.R
> +#' anl$AVAL_f <- as.factor(anl$AVAL)
I don't think this part is needed, as the below example is not ran

2022-11-10 08:14 UTC, shajoezhu commented on R/summarize_glm_count.R
> +#' @describeIn summarize_glm_count Layout creating function which can be be used for creating
I think we can move from line 411 to the end of function summarize_glm_count to the top of this script, so the documentation is clearer. As all the other parts are internal, and examples won't need to be run.

2022-11-10 08:16 UTC, shajoezhu commented on tests/testthat/test-summarize_glm_count.R
> +  anl$AVAL_f <- as.factor(anl$AVAL)
I think this part of data loading can be external to the testing functions. so the testing data can be reused, and will be more efficient.

2022-11-10 08:17 UTC, shajoezhu requested changes
Thanks @ayogasekaram ! it looks really good. I made some samll change requests. thanks!

2022-11-10 09:53 UTC, Melkiades commented on tests/testthat/test-summarize_glm_count.R
> +  anl$AVAL_f <- as.factor(anl$AVAL)
actually the libraries should be in setup_libraries and the dataset should be taken from the ones in setup_data

2022-11-10 09:55 UTC, Melkiades commented on R/summarize_glm_count.R
> +#' anl$AVAL_f <- as.factor(anl$AVAL)
I think it is needed for the last example which should be on the same doc file. Still, I would not repeat this there

2022-11-10 09:57 UTC, shajoezhu commented on tests/testthat/test-summarize_glm_count.R
> +  anl$AVAL_f <- as.factor(anl$AVAL)
Excellent! That is the proper way to do it now! Thanks @Melkiades

2022-11-10 09:58 UTC, Melkiades commented on R/summarize_glm_count.R
> +#' @describeIn summarize_glm_count Layout creating function which can be be used for creating
It makes sense but we can always put comment titles to describe the "internal" steps. Not sure. Maybe you are right and having only "runnable" docs is better

2022-11-10 10:00 UTC, Melkiades commented on inst/WORDLIST
> +quasipossion
is quasipossion a thing? sorry, I may be very ignorant here but it seems a typo to me

2022-11-10 10:04 UTC, Melkiades commented
Great job Abi!! :) I did not review it in detail, as Joe is on it, but maybe we could aim at a bit higher coverage (>90%)

2022-11-10 13:48 UTC, ayogasekaram commented on inst/WORDLIST
> +quasipossion
Good catch This was a spelling mistake in the R file. Thank you!

2022-11-10 17:19 UTC, shajoezhu commented on R/summarize_glm_count.R
> +#' anl$AVAL_f <- as.factor(anl$AVAL)
the last example has its own already

2022-11-11 07:11 UTC, shajoezhu approved these changes
changes lgtm! Thanks @ayogasekaram

2022-11-11 07:26 UTC, merged