Complete pkct01
insightsengineering/tern pull request #756
Opened 2022-11-29 17:43 UTC by Melkiades

Fixes #277

2022-12-02 15:34 UTC, edelarua reviewed
Looks great @Melkiades! Just one question about the parameter name. Can you update NEWS as well?

2022-12-02 15:34 UTC, edelarua commented on R/argument_convention.R
> +#' @param na_str (`string`)\cr used to replace all `NA` with custom `string`.
Is `na_str` the same as `na_level`? If so I would keep with the standard and use `na_level` instead.

2022-12-02 15:36 UTC, Melkiades commented on R/argument_convention.R
> +#' @param na_str (`string`)\cr used to replace all `NA` with custom `string`.
it makes sense. Done!

2022-12-02 15:46 UTC, edelarua approved these changes
Lgtm after those updates are in. Thanks @Melkiades!

2022-12-05 16:51 UTC, shajoezhu requested changes
tests/testthat/test-table_pkpct01.R should be tests/testthat/test-table_pkct01.R

2022-12-05 17:42 UTC, shajoezhu reviewed
lgtm! Thanks @Melkiades

2022-12-06 09:05 UTC, shajoezhu approved these changes
lgtm! Thanks @Melkiades

2022-12-06 10:09 UTC, shajoezhu commented
Hi @Melkiades , can you recompile the man docs

2022-12-06 15:15 UTC, merged