Add `character` method to `h_coxreg_inter_effect`
insightsengineering/tern pull request #974
Opened 2023-06-19 20:25 UTC by edelarua

Closes #968

2023-06-19 22:23 UTC, shajoezhu commented
Thanks @edelarua , blocking the merge until the 0.8.3 branch is merged

2023-06-20 07:57 UTC, shajoezhu commented on R/cox_regression_inter.R
> +  data[[covar]] <- as_factor_keep_attributes(data[[covar]], verbose = FALSE)
Hi @edelarua , I was wondering if this is necessary? 

covariates can be numeric values, right? and if it numeric, this conversion making it as factor is probably not right. 

Perhaps should check if this is variable is character first?

2023-06-20 12:32 UTC, edelarua commented on R/cox_regression_inter.R
> +  data[[covar]] <- as_factor_keep_attributes(data[[covar]], verbose = FALSE)
Thanks @shajoezhu, I have added checks for `data[[effect]]` and `data[[covar]]` being `character` variables.

2023-06-20 15:36 UTC, shajoezhu requested changes
Thanks a lot Emily!

Acutally, I was wondering if you could use liming's example in https://github.com/insightsengineering/tern/issues/968#issue-1758228287

and introduce two similar test cases here. Thanks! with two covariate variables

2023-06-21 01:55 UTC, edelarua commented
> Thanks a lot Emily!
> 
> Acutally, I was wondering if you could use liming's example in [#968 (comment)](https://github.com/insightsengineering/tern/issues/968#issue-1758228287)
> 
> and introduce two similar test cases here. Thanks! with two covariate variables

I've added in a few additional tests for these cases corresponding to Liming's examples.

2023-06-21 05:18 UTC, clarkliming commented
minor comment:

https://github.com/insightsengineering/tern/blob/605de008781809044387032074284b8e767ba87a/R/cox_regression_inter.R#L146

`levels()` should already return a character result

2023-06-21 05:22 UTC, clarkliming commented on R/cox_regression_inter.R
> +h_coxreg_inter_effect.character <- function(x,
question: is `x` also `data[[covar]]` identical?

2023-06-21 05:58 UTC, shajoezhu commented on R/cox_regression_inter.R
> +h_coxreg_inter_effect.character <- function(x,
from the help 

x | (numeric or factor)the values of the effect to be tested.
effect | (string)the name of the effect to be tested and estimated.

i was thinkin x is data[[effect]], right?

2023-06-21 06:05 UTC, clarkliming commented on R/cox_regression_inter.R
> +h_coxreg_inter_effect.character <- function(x,
![image](https://github.com/insightsengineering/tern/assets/36079400/5a498121-93db-45ac-a09e-62d711528f21)
no, `x` is `data[[covar]]`. then the documentation also need to be updated

2023-06-21 06:07 UTC, clarkliming commented on R/cox_regression_inter.R
> +h_coxreg_inter_effect.character <- function(x,
so with this we should reduce some replicated code (e.g. no need to convert data[[covar]] to factor because x should be already converted to factor

2023-06-21 07:20 UTC, clarkliming commented on R/cox_regression_inter.R
> +    level = as.character(lvl_given),
```suggestion
    term_label = paste0("  ", lvl_given),
    level = lvl_given,
```

2023-06-21 07:23 UTC, clarkliming commented on R/cox_regression_inter.R
> +
seems that `effect` variable will always be converted to factor before the execution of this.

2023-06-21 07:24 UTC, clarkliming commented on R/cox_regression_inter.R
> +
that's why in `h_coxreg_inter_effect.factor` there is no such code. also note that the S3 dispatch is only dependent on the first variable class

2023-06-21 07:37 UTC, clarkliming commented on R/cox_regression_inter.R
> +  y <- as_factor_keep_attributes(x, verbose = verbose)
will it introduce "<Missing>" as a new level? probably a "as.factor" or "factor" should be sufficient

2023-06-21 07:48 UTC, shajoezhu commented on R/cox_regression_inter.R
> +  y <- as_factor_keep_attributes(x, verbose = verbose)
it might drop the attribute content, right? as the conent

2023-06-21 07:52 UTC, clarkliming commented on R/cox_regression_inter.R
> +  y <- as_factor_keep_attributes(x, verbose = verbose)
the attribute does not matter here; anyway it is not used . my typo in previous reply, that "<Missing>" could be introduced

2023-06-21 07:52 UTC, clarkliming commented on R/cox_regression_inter.R
> +  y <- as_factor_keep_attributes(x, verbose = verbose)
it is <Missing>

2023-06-21 07:52 UTC, clarkliming commented on R/cox_regression_inter.R
> +  y <- as_factor_keep_attributes(x, verbose = verbose)
it is `\<Missing\>`

2023-06-21 15:55 UTC, clarkliming approved these changes
looks good to me!

2023-06-22 00:54 UTC, shajoezhu approved these changes
lgtm! Thanks @edelarua

2023-06-22 00:54 UTC, merged